force-app/main/default/objects/Product_Geo_Mapping__mdt/Product_Geo_Mapping__mdt.object-meta.xml
<CustomObject>
    <description
  >Metadata to map Products to the minimum permissible fly zones in different countries.</description>
    <label>Product Geo Mapping</label>
    <pluralLabel>Product Geo Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Permissible_Fly_Zone__c.field-meta.xml
<CustomField>
    <fullName>Permissible_Fly_Zone__c</fullName>
    <description>allowed area&apos;s for specific air craft</description>
    <label>Permissible Fly Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended</fullName>
                <default>true</default>
                <label>Recommended</label>
            </value>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductZoningService.cls
@RestResource(urlMapping='/ProductZoning/*')
global with sharing class ProductZoningService {
  @HttpGet
  global static String getFlyZone() {
    RestRequest req = RestContext.request;
    Map<String, String> queryParams = req.params;
    String productCode = queryParams.get('ProductCode');

    String countryCode = req.headers.get('CountryCode');

    if (countryCode == null) {
      countryCode = 'US'; // Use 'US' as the default country code
    }

    if (String.isBlank(productCode)) {
      return 'ProductCode is missing or doesn\'t exist';
    }

    List<Product2> products = [
      SELECT Id, Family
      FROM Product2
      WHERE ProductCode = :productCode
      LIMIT 1
    ];
    if (products.isEmpty()) {
      return 'ProductCode is missing or doesn\'t exist';
    }

    String productFamily = products[0].Family;

    List<Product_Geo_Mapping__mdt> mappings = [
      SELECT Permissible_Fly_Zone__c
      FROM Product_Geo_Mapping__mdt
      WHERE
        Product_Family__c = :productFamily
        AND Country_Code__c = :countryCode
      LIMIT 1
    ];

    if (!mappings.isEmpty()) {
      return mappings[0].Permissible_Fly_Zone__c;
    } else {
      return 'Confirm with the local authorities';
    }
  }
}