force-app/main/default/objects/Claim__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Injury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <description>Types of coverage available</description>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Flyaway</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetService.cls
@RestResource(urlMapping='/lost')
global with sharing class AssetService {
  @HttpPost
  global static String reportLostDevice(String assetIdentifier) {
    List<Asset> assets = [
      SELECT
        Id,
        (
          SELECT Id
          FROM Insurances__r
          WHERE Coverage__c = 'Comprehensive'
          LIMIT 1
        ),
        (
          SELECT Name
          FROM Claims__r
          WHERE Type__c = 'Loss'
          LIMIT 1
        )
      FROM Asset
      WHERE Asset_Identifier__c = :assetIdentifier
      LIMIT 1
    ];

    Asset asset = assets.size() == 1 ? assets[0] : null;
    if (asset == null) {
      return 'No device found.';
    }

    Insurance__c comprehensiveInsurance = asset.Insurances__r?.size() > 0
      ? asset.Insurances__r[0]
      : null;
    Claim__c existingLossClaim = asset.Claims__r?.size() > 0
      ? asset.Claims__r[0]
      : null;

    asset.Status = 'Lost';
    update asset;

    if (comprehensiveInsurance == null) {
      return 'No coverage. Asset status adjusted to Lost.';
    }

    String claimName;

    if (existingLossClaim == null) {
      Claim__c newClaim = new Claim__c(
        Type__c = 'Loss',
        Asset__c = asset.Id,
        Insurance__c = comprehensiveInsurance.Id
      );
      insert newClaim;

      newClaim = [SELECT Name FROM Claim__c WHERE Id = :newClaim.Id LIMIT 1];
      claimName = newClaim.Name;
    } else {
      claimName = existingLossClaim.Name + 'already filed.';
    }

    return claimName;
  }
}